################################# Default configuration ###################
baseURL = "https://jtb.netlify.app"
title = "Just Thai Boston"
theme = "jtb"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

################################# Outputs #################################
# hugo outputs
[outputs]
home = [ "HTML", "RSS"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/JustThai2.svg"
# Meta data
description = "This is Just Thai Boston"
author = "JustThai"
# Contact Information
phone = "617.288.6388"
mobile = "617.288.6225"
#email = "demo@email.com"
location = "1512A Dorchester Ave Dorchester, MA 02122"
hour = "Sun 12:00pm - 9:30pm"
monthur = "Mon - Thur 11:00am - 9:30pm"
frisat = "Fri - Sat 11:00am - 10:00pm"
# contact form action
contact_form_action = "https://formspree.io/xgenqokj" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "42.299065"
map_longitude = "-71.060395"
map_marker = "images/marker.png"

  
############################# social site ########################
[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/justthaiboston"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/Just-Thai-Boston-100503341771699"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/justthaiboston"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 [Just Thai](https://justthaiboston.com) All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Project"
URL = "project"
weight = 3

[[Languages.en.menu.main]]
name = "Service"
URL = "service"
weight = 4

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

[[Languages.en.menu.main]]
weight = 6
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Pricing"
  URL = "pricing"
  
[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 7

[[Languages.en.menu.main]]
name = "Menu"
URL = "menu"
weight = 8


# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[Languages.en.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[Languages.en.menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

[[Languages.en.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6

